name: route
version: 0.5.0
author: Dart Authors <misc@dartlang.org>
description: A client + server routing library for Dart
homepage: https://github.com/dart-lang/route
environment:
  sdk: '>=0.8.0'
dependencies:
  logging: any
  uri: '>=0.8.0'
  quiver: '>=0.17.0'
dev_dependencies:
  barback: any
  browser: any
  mdv: any
  observe: any
  unittest: any
  polymer: any
  polymer_expressions: any
