name: route
version: 0.5.0
author: Dart Authors <misc@dartlang.org>
description: A client + server routing library for Dart
homepage: https://github.com/dart-lang/route
environment:
  sdk: '>=0.5.12'
dependencies:
  logging: any
  uri_template:
    path: /Users/justinfagnani/Documents/Projects/urit2
dev_dependencies:
  browser: any
  fancy_syntax:
    path: /Users/justinfagnani/Documents/Projects/fancy-syntax
  mdv: any
  observe: any
  unittest: any
  polymer:
    path: /Users/justinfagnani/Documents/Projects/web-ui
